version: '3.8'

services:
  db:
    image: postgres:15
    container_name: api-reembolsos
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: juanribeiro
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"    # endpoint único para todos os serviços AWS no LocalStack
      - "4571:4571"    # UI do LocalStack, opcional
    environment:
      - SERVICES=lambda,sqs,sns
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  pgdata:
  minio-data:
