services:
  db:
    image: postgres:15
    container_name: api-reembolsos
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: juanribeiro
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
